name: Deploy Deno to Azure Function App

on:
  [workflow_dispatch]

env:
  AZURE_FUNCTIONAPP_NAME: denofunc-linux-dynamic    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1 # Installs latest version

      - name: install denofunc
        run: |
          deno install --allow-run --allow-read --allow-write --allow-net --unstable --force --name=denofunc https://raw.githubusercontent.com/anthonychu/azure-functions-deno-worker/v0.9.0/denofunc.ts

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build custom handler
        run: |
          echo pwd
          pwd
          echo pushd
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          echo pwd
          pwd
          echo ls
          ls -l
          echo which func
          PATH=.:$PATH which func
          echo chmod 
          chmod +x func
          echo denofunc
          PATH=.:$PATH denofunc publish ${{ env.AZURE_FUNCTIONAPP_NAME }}
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}